### ISSUE TITLE
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by Quasindro** [Syranda/Cardinal#1]
> [16:23:58 INFO]: [Cardinal] Enabling Cardinal v1.3
> [16:23:58 WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 1000 bytes
> [16:23:58 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> [16:23:58 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> [16:23:58 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> [16:23:58 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
> [16:23:58 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
> [16:23:58 WARN]:        at com.mysql.jdbc.Util.getInstance(Util.java:387)
> [16:23:58 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941)
> [16:23:58 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
> [16:23:58 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
> [16:23:58 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
> [16:23:58 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
> [16:23:58 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
> [16:23:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
> [16:23:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
> [16:23:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
> [16:23:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
> [16:23:58 WARN]:        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
> [16:23:58 WARN]:        at de.syranda.spidermysql.customclasses.ConnectionManager.insertStatement(ConnectionManager.java:39)
> [16:23:58 WARN]:        at de.syranda.spidermysql.customclasses.builder.TableBuilder.build(TableBuilder.java:232)
> [16:23:58 WARN]:        at de.syranda.cardinal.customclasses.Cardinal.loadCardinal(Cardinal.java:508)
> [16:23:58 WARN]:        at de.syranda.cardinal.plugin.Main.onEnable(Main.java:111)
> [16:23:58 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
> [16:23:58 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
> [16:23:58 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
> [16:23:58 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362)
> [16:23:58 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322)
> [16:23:58 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
> [16:23:58 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
> [16:23:58 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
> [16:23:58 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
> [16:23:58 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
> [16:23:58 WARN]:        at java.lang.Thread.run(Unknown Source)

Keeps happening on startup, code was compiled from the cloned master repository.

**Comment by Syranda** [comment]
Make sure you're using InnoDB as engine

**Comment by Quasindro** [comment]
Why doesn't your builder do it? Why is there no `ENGINE=InnoDB` clause in the `CREATE TABLE` statement?
It's true that I should have setup my phpMyAdmin properly but you know how it is.

**Comment by Syranda** [comment]
I'll implement it in future version of the MySQL API.

**Comment by Quasindro** [comment]
Great. I'm not sure if issuers can close issues on the projects but we can assume this one as resolved. Cardinal is pretty amazing by the way.

**Comment by Syranda** [comment]
Thank you :3
